import Head from 'next/head'
import Image from 'next/image'
import About from '../components/about'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Odyssey Africa Hikes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Odyssey Africa Hikes' slogan='Travel in Style'/>
      <About />
    </div>
  )
}
